### ISSUE TITLE
How close to drop in?

### ISSUE THREAD

**Issue by shadowcat-mst** [SuiteSetup/net-google-calendar#1]
Hey, so, surprise surprise, we managed to have an in-house script that uses the old API, which is kinda gone.

Your code seems to be mostly following the style of the Net::Google::Calendar module interface-wise, so I was wondering - how close is it? I mean, I'm not expecting to just replace a 'use' call and be home free, nice though that would be, but I'd like a read on how much more than that I'm likely to need.

The code in question is basically two scripts - one that adds an entry, and one that fetches events and archives them into a local sqlite db - so nothing particularly clever.

Note: I've skimmed the current code. It looks gorgeous. I'm ok with us having to RTFS for the moment - I just need to figure out how much, because we can _probably_ just ditch the gcal integration in the relevant code if we have to.

Thoughts? (and sorry for abusing your issue list to ask this)

**Comment by rhesa** [comment]
Hi, thanks for the kind words!

I initially had hoped to make the interfaces compatible, but it turns out the data model on Google's end changed more than I expected, and I didn't feel like shoehorning it into the v2 model. So they two did diverge a bit, mostly in Event data type.

Since I'm only using this internally, I haven't set aside time to document it. I really should ;)

What we use it for is full sync of events: 
- add/update/delete events locally coming from google calendar
- add/update/delete events on google calendar that were added locally

First thing to do is find the calendar you're interested in:

```
my $gcal = Net::Google::CalendarV3->new();
$gcal->set_calendar($google_calendar_id); # typically your gmail address
```

Now to get new events since a certain date:

```
my @events = $gcal->get_events( updatedMin => "2014-11-17T00:00:00Z" );
```

This gives you a list of Net::Google::CalendarV3::Event objects. They have a (crude) TO_JSON method, so you can easily dump them.

To create a new event on your Google Calendar, you create a new Event object:

```
my $entry = Net::Google::CalendarV3::Event->new();

$entry->title($title);
$entry->status('confirmed');
$entry->when($start_date, $end_date, $is_all_day);

my $new = $gcal->add_entry($entry) or die;
```

That's the basics.

There are attributes for most of the things Google defines for events. See https://developers.google.com/google-apps/calendar/v3/reference/events for the full model, and for now, see the implementation of Event.pm for what I support.

**Comment by idnorton** [comment]
Could you give me a pointer on where the oauth calls fit into this example please?

Thanks, Ian.

**Comment by rhesa** [comment]
If you supply a valid "oauth2_access_token" to the constructor, every API call is authenticated. That is a shortcut I added for my own convenience:

```
my $gcal = Net::Google::CalendarV3->new( oauth2_access_token => "foo" );
```

The alternative would be to use the authentication features of WWW::JSON. You can supply that through the "authentication" attribute, via the constructor.

```
my $gcal = Net::Google::CalendarV3->new( authentication => { Basic => { username => 'antipasta', password => 'hunter2' } } );
```

Note that I've not used WWW::JSON's way of authenticating. Net::OAuth2 looked too complicated to me, so I rolled my own.

**Comment by castaway** [comment]
Hrm.. I can't seem to get this working with either an access token or the Basic => {} example above.. in both cases I get a 401 Login Required.. in the contents of the http response there's a : 'client-warning' => 'Unsupported authentication scheme \'bearer\'' .. which is confusing!

Do we need to create an application on the google developer console and turn on the calendar api and get a client id/secret and... all that jazz, to use the v3 API?

**Comment by rhesa** [comment]
Yes, you do need to do the full app ritual to be able to use OAuth2, and I believe that's the only authentication mechanism Google supports these days: https://developers.google.com/google-apps/calendar/auth

**Comment by castaway** [comment]
Soo.. how would the Basic example work then, it doesn't have a client id etc?

**Comment by rhesa** [comment]
It wouldn't, forget I gave that example ;)

If you're going to use Net::OAuth2 to do your token management, then you could use that module to do the authentication through WWW::JSON with

```
my $gcal = Net::Google::CalendarV3->new( authentication => { OAuth2 => Net::OAuth2::AccessToken->new( ... ) } );
```

In my case, I already had oauth code lying around, so I found it easier to just pass in the access token I already had.

**Comment by castaway** [comment]
So after much fun with OAuth2 (yay!) - ended up using Google::API::OAuth2::Client which seems to mostly work.. I have some more questions ;)

1) Do you have any idea if its possible to get an access_token with a longer expiry than 3600 sec? (mst insisted I ask this one ;)
2) CalendarV3 doesnt allow me to change/edit the access_token once its created (you store it in the _service and the authentication attrs which are 'ro') - does it seem sane just to create a new instance if we get a refreshed token?

**Comment by rhesa** [comment]
1) Google doesn't say what their limit is: https://developers.google.com/accounts/docs/OAuth2#expiration only says "access_tokens have limited lifetimes".  https://developers.google.com/accounts/docs/OAuth2WebServer#refresh has more details on the oauth process, but I don't see any option to specify expiries.

2) I'd create a new instance, yes. I do that all the time, in fact. Our app syncs calendars for thousands of users and that works fine. For us at least, Moose etc poses little overhead.

**Comment by nigelhorne** [comment]
Thanks for this information.  I'm battling with trying to reconcile the man page for Net::OAuth2::AccessToken with what the Google dashboard provides.  How do the field names match?  Is there any example code?
