### ISSUE TITLE
"400 Bad Request" - floating timezones

### ISSUE THREAD

**Issue by castaway** [SuiteSetup/net-google-calendar#2]
If we pass a DateTime object with a floating timezone as a date, for example in (Event) $e->when($start , $end, 0); Then we just get a "400 Bad Request" back from add_event. If floating doesn't work, could you add a specific warning about it or something?

**Comment by rhesa** [comment]
That's curious, since I already have code to deal with floating time zones (and I actually use them in production). See Date->set for details. Could you provide more details?

**Comment by castaway** [comment]
I see that you're checking ->time_zone eq 'floating', I tried the same and it doesn't return true, we need time_zone->is_floating or ->time_zone->name eq 'floating'

When my date is set as a ::CalendarV3::Date, it does end up with the timeZone set to floating: 

'start' => bless( {
              'timeZone' => 'floating',
              'dateTime' => '2014-11-25T09:00:00'
             }, 
      'Net::Google::CalendarV3::Date' )

Possibly its the DateTime::TimeZone version? I'm on 1.46 at the moment.

**Comment by rhesa** [comment]
Oh, I see! I'll change it to time_zone->is_floating.
